name: ems

services:
  nginx:
    image: ghcr.io/mktkhr/stamp-iot/nginx:latest
    container_name: nginx
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ${SSL_PATH}/ssl
        target: /etc/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - ems-network

networks:
  ems-network:
    name: ems-network
    driver: bridge
    external: true
