version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    expose:
      - '5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: "ems_db"

  redis:
    image: redis:7
    container_name: redis
    expose:
      - '6379'
    volumes:
      - redis-db:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - /home/ems/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ems/deploy/frontend/dist:/usr/share/nginx/dist

volumes:
  postgres-db:
  redis-db:
  redisinsight:
