version: "3.9"
services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: "ems_db"

  redis:
    image: redis:7.2.3
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis-db
        target: /data

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /home/ems/deploy/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: /home/ems/deploy/frontend/dist
        target: /usr/share/nginx/dist
      - type: bind
        source: /home/ems/ssl
        target: /etc/ssl
    depends_on:
      - java

  java:
    image: amazoncorretto:21.0.1
    container_name: java
    tty: true
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: /home/ems/deploy/backend
        target: /app/backend
    working_dir: /app/backend
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASS: ${POSTGRES_DB_PASS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    command: /bin/bash -c "POSTGRES_DB_USER=${POSTGRES_DB_USER} POSTGRES_DB_PASS=${POSTGRES_DB_PASS} REDIS_HOST=${REDIS_HOST} REDIS_PORT=${REDIS_PORT} java -jar /app/backend/server.jar --spring.profiles.active=prod"

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - /home/ems/ssl:/etc/letsencrypt
      - /home/ems/deploy/frontend/dist:/usr/share/nginx/dist
    command: ["--version"]

volumes:
  postgres-db:
  redis-db:
