version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ems_db"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379
    volumes:
      - redis-db:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/dist
      - ./docker/local/nginx/log:/var/log/nginx
    depends_on:
      - java

  java:
    image: amazoncorretto:17
    container_name: java
    tty: true
    ports:
      - 8082:8082
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./backend
        target: /app/backend
    working_dir: /app/backend
    command: /bin/bash -c "./gradlew bootRun --build-cache"

volumes:
  postgres-db:
  redis-db:
  redisinsight:
