version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${{ POSTGRES_DB_USER }}
      POSTGRES_PASSWORD: ${{ POSTGRES_DB_PASS }}
      POSTGRES_DB: "ems_db"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-db:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/dist

  java:
    image: amazoncorretto:17
    container_name: java
    ports:
      - 8082:8082
    volumes:
      - ./backend/server:/usr/src:cached

volumes:
  postgres-db:
  redis-db:
  redisinsight:
