version: "3"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: "ems_db"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'
    volumes:
      - redisinsight:/db
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
      - '443:443'
    extra_hosts:
      - "host.docker.internal:host-gateway" #コンテナからホストにアクセスするために必要
    volumes:
      - /home/ems/deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ems/deploy/frontend/dist:/usr/share/nginx/dist
      - /home/ems/ssl:/etc/ssl

  certbot:
      image: certbot/certbot:v1.7.0
      volumes:
        - /home/ems/ssl:/etc/letsencrypt
        - /home/ems/deploy/frontend/dist:/usr/share/nginx/dist
      command: ["--version"]

volumes:
  postgres-db:
  redis-db:
  redisinsight:
