apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java
          image: {{ .Values.java.image }}
          command:
            - "java"
            - "-jar"
            - "server.jar"
            - "--spring.profiles.active=prod"
          ports:
            - containerPort: {{ .Values.java.port }}
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: stamp-iot-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 10001
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.java.actuator.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.java.actuator.port }}
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
