apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: {{ .Values.namespace }}
  labels:
    app: java
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.java.port }}
      targetPort: {{ .Values.java.port }}
      protocol: TCP
  selector:
    app: java-app
