version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "stamp_db"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:1.12.0
    ports:
      - 8005:8001
    volumes:
      - redisinsight:/db
    depends_on:
      - redis
volumes:
  db-store:
  redisinsight: