# Grafana
grafana:
  host: monitor.ems-engineering.site
  replicaCount: 1
  envFromSecret: stamp-iot-grafana-secret
  admin:
    existingSecret: stamp-iot-grafana-secret
    userKey: GF_SECURITY_ADMIN_USER
    passwordKey: GF_SECURITY_ADMIN_PASSWORD
  ingress:
    enabled: false
  persistence:
    enabled: true
    existingClaim: grafana-pvc

# Prometheus
nodeExporter:
  enabled: true

# Loki
loki:
  persistence:
    enabled: true
    existingClaim: loki-pvc

# Promtail
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push