namespace: stamp-iot

nginx:
  image: "ghcr.io/mktkhr/stamp-iot/nginx:0617f35"
  port: 8080
  replicas:
    min: 1
    max: 3

java:
  image: "ghcr.io/mktkhr/stamp-iot/java:manual-arm"
  port: 8082
  actuator:
    port: 7082
  replicas:
    min: 1
    max: 3

ingress:
  host: www.ems-engineering.jp
