@startuml stamp-iot 
entity "AccountTable" {
    +uuid : UUID<<PK>>
    --
    mail_address : VARCHAR(255)
    password : VARCHAR(255)
    name : VARCHAR(255)
    created_at : LOCALDATETIME
    updated_at : LOCALDATETIME
    deleted_at : LOCALDATETIME
}

entity "MicroControllerTable" {
    +uuid : UUID<<PK>>
    account_uuid : UUID<<FK>>
    --
    mac_address : VARCHAR(255)
    created_at : LOCALDATETIME
    updated_at : LOCALDATETIME
    deleted_at : LOCALDATETIME
}

entity "MeasuredDataMasterTable" {
    +uuid : UUID<<PK>>
    micro_controller_uuid : UUID<<FK>>
    --
    measuring_time : LOCALDATETIME
    day_of_year : VARCHAR(255)
    voltage : VARCHAR(255)
    created_at : LOCALDATETIME
    updated_at : LOCALDATETIME
    deleted_at : LOCALDATETIME
}

entity "Sdi12DataTable" {
    +id : BINGINT AUTO INCREMENT<<PK>>
    measured_data_master_uuid : UUID<<FK>>
    sensor_id : INT<<FK>>
    --
    sdi_address : VARCHAR(1)
    volumetric_water_content : VARCHAR(255)
    soil_temperature : VARCHAR(255)
    bulk_relative_permittivity : VARCHAR(255)
    soil_bulk_electric_conductivity : VARCHAR(255)
    soil_pore_water_electric_conductivity : VARCHAR(255)
    gravitational_acceleration_x_axis : VARCHAR(255)
    gravitational_acceleration_y_axis : VARCHAR(255)
    gravitational_acceleration_z_axis : VARCHAR(255)
}

entity "EnvironmentalDataTable" {
    +id : BINGINT AUTO INCREMENT<<PK>>
    measured_data_master_uuid : UUID<<FK>>
    --
    atmospheric_pressure : VARCHAR(255)
    temperature : VARCHAR(255)
    relative_humidity : VARCHAR(255)
    co2_concentration : VARCHAR(255)
    total_valatile_organic_compounds : VARCHAR(255)
    analog_value : VARCHAR(255)
}

entity "SensorTable" {
    +id : INT<<PK>>
    --
    sensor_name : VARCHAR(255)
    vender_name : VARCHAR(255)
    identification_code : VARCHAR(255)
}

AccountTable ||-d-o{ MicroControllerTable
MicroControllerTable ||-r-o{ MeasuredDataMasterTable
MeasuredDataMasterTable ||-r-o{ Sdi12DataTable
MeasuredDataMasterTable ||-r-o{ EnvironmentalDataTable
Sdi12DataTable ||-r-o{ SensorTable

@enduml