apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stamp-iot-grafana
spec:
  acme:
    email: j39g8bxh@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-stamp-iot-grafana-account-key
    solvers:
      - http01:
          ingress:
            class: nginx