apiVersion: v1
kind: ConfigMap
metadata:
  name: stamp-iot-datasource-configmap
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: k8s-prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
        isDefault: true