apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.alloy: |
    logging {
      level = "info"
    }

    loki.write {
      endpoint {
        url = "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    local.file_match "container-logs" {
      path_targets = [
        "/var/log/pods/*/*/*.log"
      ]
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.write.default.receiver]
      include_container_logs = true
    }
