spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  flyway:
    enabled: true
    locations: classpath:db/migration

# actuator
management:
  server:
    port: 7082
  endpoint:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics