name: Java CI
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.build-test.yaml"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build/Test
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "corretto"
          cache: "gradle"

      - name: Run build
        run: ./gradlew build
        working-directory: ./backend

      - name: Run unit test
        run: ./gradlew test
        working-directory: ./backend

      - name: Copy Jar file
        run: mv ./backend/build/libs/server.jar server.jar

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: server.jar

  build-image:
    name: Docker Image Build
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-file
          path: ./backend

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USER_NAME}}
          password: ${{secrets.GHCR_ACCESS_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare build tag
        id: tag
        run: |
          VERSION=`echo ${GITHUB_REF#refs/tags/} | grep -o '[0-9]*\..*'`
          COMMITID=$(git rev-parse --short ${{ github.sha }})
          IMAGE=ghcr.io/mktkhr/stamp-iot/backend-java
          TAGS=`echo ${IMAGE}:latest --tag ${IMAGE}:${VERSION}`
          echo ::set-output name=TAGS::${TAGS}

      - name: test
        run: |
          pwd
          ls
          ls ./backend

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
