name: Java CD
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Java Deploy
    runs-on: [self-hosted]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # NOTE: 開発環境はlatest運用のため，imageを明示的にpullする
      - name: Docker image pull
        run: echo $EMS_PASS | sudo -S docker compose -f docker-backend-compose.yaml pull

      - name: Stop docker service
        run: cd /usr/share/deploy && echo $EMS_PASS | sudo -S docker compose -f docker-backend-compose.yaml down

      - name: Start docker service
        run: cd /usr/share/deploy && echo $EMS_PASS | sudo -S docker compose -f docker-backend-compose.yaml up -d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
