name: Node.js CI
on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.build-test.yaml"
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    name: Build/Test
    runs-on: [self-hosted]
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [20.15.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install packages
        run: |
          npm install -g yarn
          yarn
        working-directory: ./frontend

      - name: Run build
        run: yarn build:prod
        working-directory: ./frontend

      - name: Run unit test
        run: yarn test:unit
        working-directory: ./frontend

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            ./frontend/dist
            !./frontend/dist/**/*.md

  build-image:
    name: Docker image build
    runs-on: [self-hosted]
    timeout-minutes: 30
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./frontend/dist

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.GHCR_USER_NAME}}
          password: ${{secrets.GHCR_ACCESS_TOKEN}}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta(DEV)
        id: meta-dev
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/mktkhr/stamp-iot/nginx-dev
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build and push(DEV)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-dev.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker meta(PROD)
        id: meta-prod
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/mktkhr/stamp-iot/nginx
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short

      - name: Build and push(PROD)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile-eks
          push: true
          tags: ${{ steps.meta-prod.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  screenshot-main:
    name: Take Expected Screenshots At Main Branch
    runs-on: [self-hosted]
    timeout-minutes: 30
    needs: build

    strategy:
      matrix:
        node-version: [20.15.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # スクリーンショットのキャッシュの有無を評価する
      - name: Restore cached expected screenshots
        id: expected_screenshots_cache
        uses: ./.github/workflows/composite/frontend-cache-screenshot

      # 以下はキャッシュが存在しなかった場合に実行される
      - name: Use Node.js ${{ matrix.node-version }}
        if: ${{ steps.expected_screenshots_cache.outputs.cache-hit != 'true'}}
        uses: ./.github/workflows/composite/frontend-setup

      - name: Restore or build storybook # キャッシュにスクショが保存されてなかったらStorybookをビルドしてスクショ撮影する
        if: ${{ steps.expected_screenshots_cache.outputs.cache-hit != 'true'}}
        uses: ./.github/workflows/composite/frontend-cache-storybook-static

      - name: Take expected screenshots
        if: ${{ steps.expected_screenshots_cache.outputs.cache-hit != 'true'}}
        run: yarn storycap:ci
        working-directory: ./frontend

      - name: Upload expected screenshots to artifact
        uses: actions/upload-artifact@v4

        with:
          name: expected-screenshots
          path: __screenshots__
          retention-days: 30

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
