name: Nginx CD
on:
  push:
    paths:
      - 'docker/production/nginx/**'
      - '.github/workflows/github-action.nginx.yml'

jobs:
  deploy:
    name: Nginx Deploy
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: docker/production/nginx/nginx.conf
      - name: Create directory for download artifacts
        run: mkdir -p /usr/share/tmp/nginx/${{ github.ref_name }}/
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /usr/share/tmp/nginx/${{ github.ref_name }}/
      - name: Copy artifacts
        run: cp -rp /usr/share/tmp/nginx/${{ github.ref_name }}/artifact/nginx.conf /usr/share/deploy/nginx/nginx.conf

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true