name: Node.js CI/CD
on:
  push:
    # branches:
    #   - main

jobs:
  build:
    name: Build
    runs-on: [self-hosted]

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm install
        working-directory: ./frontend
      - run: npm run build --if-present
        working-directory: ./frontend

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            ./frontend//dist
            !./frontend/dist/**/*.md

  deploy:
    name: Deploy
    runs-on: [self-hosted]
    needs: build

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: /home/ems/tmp/frontend/${{ github.ref_name }}

      - name: Copy artifacts
        run: cp -rp /home/ems/tmp/frontend/${{ github.ref_name }} /home/ems/deploy/frontend/${{ github.ref_name }}
      - name: Link artifacts to content
        run: ln -fns content /home/ems/deploy/frontend/${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
