name: CD
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
    needs: build

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: /home/ems/tmp/frontend/${{ github.ref_name }}

      - name: Copy artifacts
        run: cp /home/ems/tmp/frontend/${{ github.ref_name }} /home/ems/deploy/frontend/${{ github.ref_name }}
      - name: Link artifacts to content
        run: ln -fns content /home/ems/deploy/frontend/${{ github.ref_name }}