name: docker-compose CD
on:
  push:
    paths:
      - docker-compose-prod.yaml
      - '.github/workflows/github-action.docker.yml'

jobs:
  deploy:
    name: docker-compose Deploy
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: docker-compose-prod.yaml
      - name: Create directory for download artifacts
        run: mkdir -p /home/ems/tmp/docker/${{ github.ref_name }}/
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /home/ems/tmp/docker/${{ github.ref_name }}/
      - name: Create directory for deploy
        run: mkdir -p /home/ems/deploy/docker/${{ github.ref_name }}/
      - name: Copy artifacts
        run: cp -rp /home/ems/tmp/docker/${{ github.ref_name }}/artifact/* /home/ems/deploy/docker/${{ github.ref_name }}
      - name: Link artifacts to docker-compose-prod.yaml
        run: ln -fns /home/ems/deploy/docker/${{ github.ref_name }}/docker-compose-prod.yaml /home/ems/deploy/docker/docker-compose-prod.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
