name: docker-compose CD
on:
  push:
    paths:
      - docker-compose-prod.yaml
      - '.github/workflows/github-action.docker.yml'

jobs:
  deploy:
    name: docker-compose Deploy
    runs-on: [self-hosted]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: docker-compose-prod.yaml
      - name: Create directory for download artifacts
        run: mkdir -p /usr/share/tmp/docker/${{ github.ref_name }}/
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /usr/share/tmp/docker/${{ github.ref_name }}/
      - name: Copy artifacts
        run: cp -rp /usr/share/tmp/docker/${{ github.ref_name }}/artifact/docker-compose-prod.yaml /usr/share/deploy/docker/docker-compose-prod.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
