name: Java CI/CD
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/github-action.backend.yml'

jobs:
  build:
    name: Java Build/Test
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run build
        run: ./gradlew build
        working-directory: ./backend
      - name: Run unit test
        run: ./gradlew test
        working-directory: ./backend
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: cancelled() != true
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./backend/build/libs/server.jar

  deploy:
    name: Java Deploy
    runs-on: [self-hosted]
    needs: build

    steps:
      - name: Create directory for download artifacts
        run: mkdir -p /home/ems/tmp/backend/${{ github.ref_name }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /home/ems/tmp/backend/${{ github.ref_name }}
      - name: Create directory for deploy
        run: mkdir -p /home/ems/deploy/backend/${{ github.ref_name }}
      - name: Copy artifacts
        run: cp -rp /home/ems/tmp/backend/${{ github.ref_name }}/artifact/server.jar /home/ems/deploy/backend/${{ github.ref_name }}
      - name: Link artifacts to server.jar
        run: ln -fns /home/ems/deploy/backend/${{ github.ref_name }}/server.jar /home/ems/deploy/backend/jar/server.jar

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true