name: Node.js CI/CD
on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/github-action.frontend.yml'

jobs:
  build:
    name: Node.js Build
    runs-on: [self-hosted]
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json
      - run: npm install
        working-directory: ./frontend
      - run: npm run build:prod --if-present
        working-directory: ./frontend

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            ./frontend/dist
            !./frontend/dist/**/*.md

  deploy:
    name: Node.js Deploy
    runs-on: [self-hosted]
    timeout-minutes: 30
    needs: build

    steps:
      - name: Create directory for download artifacts
        run: mkdir -p /home/ems/tmp/frontend/${{ github.ref_name }}/dist
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: /home/ems/tmp/frontend/${{ github.ref_name }}/dist
      - name: Create directory for deploy
        run: mkdir -p /home/ems/deploy/frontend/${{ github.ref_name }}
      - name: Copy artifacts
        run: cp -rp /home/ems/tmp/frontend/${{ github.ref_name }}/* /home/ems/deploy/frontend/${{ github.ref_name }}
      - name: Link artifacts to dist
        run: ln -fns /home/ems/deploy/frontend/${{ github.ref_name }}/dist /home/ems/deploy/frontend/dist

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
